/**
 * JiuSpeak AI — Seed: "English for Jiu-Jitsu" (100 aulas, 5 módulos)
 * Baseado no livro completo de roteiros das Prof.ª Raphaela e Prof.ª Rebeca
 * 
 * INSTRUÇÕES:
 * Este arquivo exporta a função seedCurriculum(db) que deve ser chamada
 * dentro do seedInitialData() em repository.ts
 * 
 * Sobe em: /var/www/jiuspeak-ai/src/db/seed-curriculum.ts
 */

export function seedCurriculum(db: any) {
  const now = new Date().toISOString();

  // ========== 5 COURSES (1 per module/belt) ==========
  const courses = [
    { id: 'crs-white-belt', title: 'Module 1: WHITE BELT — Survival English', desc: 'Vocabulário essencial para treinar em qualquer academia do mundo. 20 aulas com Prof.ª Raphaela.', belt: 'White' },
    { id: 'crs-blue-belt', title: 'Module 2: BLUE BELT — Technique English', desc: 'Compreender técnicas, posições e instruções durante o treino. 20 aulas com Prof.ª Rebeca.', belt: 'Blue' },
    { id: 'crs-purple-belt', title: 'Module 3: PURPLE BELT — Submission English', desc: 'Explicar e compreender finalizações, alavancas e correções em inglês. 20 aulas com Prof.ª Raphaela.', belt: 'Purple' },
    { id: 'crs-brown-belt', title: 'Module 4: BROWN BELT — Competition English', desc: 'Competir e se comunicar internacionalmente em campeonatos de Jiu-Jitsu. 20 aulas com Prof.ª Rebeca.', belt: 'Brown' },
    { id: 'crs-black-belt', title: 'Module 5: BLACK BELT — Instructor English', desc: 'Ensinar Jiu-Jitsu totalmente em inglês, ministrar seminários e gerir academias. 20 aulas com Prof.ª Raphaela.', belt: 'Black' },
  ];

  for (const c of courses) {
    db.run(
      `INSERT OR IGNORE INTO courses (id, title, descriptionPt, targetBelt, isOfficialJiuSpeakContent, createdAt) VALUES (?, ?, ?, ?, 1, ?)`,
      [c.id, c.title, c.desc, c.belt, now]
    );
  }

  // ========== 100 LESSONS ==========
  const lessons = [
    // ─── MODULE 1: WHITE BELT (Survival English) ───
    { id: 'lsn-01', courseId: 'crs-white-belt', order: 1, title: 'Mat Etiquette', summaryPt: 'Etiqueta no tatame: saudar o espaço, higiene, kimono limpo.',
      phrases: [{ phrase: 'Bow to the mat', translation: 'Saudar o tatame' }, { phrase: 'Take off your shoes before stepping on the mat', translation: 'Tire os calçados antes de pisar no tatame' }, { phrase: 'Keep your nails trimmed', translation: 'Mantenha as unhas cortadas' }, { phrase: 'Always wear a clean Gi', translation: 'Use sempre um kimono limpo' }],
      dialogue: [{ speaker: 'Raphaela', textEn: 'The first thing you do when stepping onto the mat is to bow.', textPt: 'A primeira coisa ao entrar no tatame é saudar.' }] },
    { id: 'lsn-02', courseId: 'crs-white-belt', order: 2, title: 'Greetings & Introductions', summaryPt: 'Cumprimentos e apresentações na academia.',
      phrases: [{ phrase: 'Good morning / Good afternoon / Good evening', translation: 'Bom dia / Boa tarde / Boa noite' }, { phrase: 'Nice to meet you', translation: 'Prazer em conhecê-lo' }, { phrase: 'What is your name?', translation: 'Qual é o seu nome?' }, { phrase: 'Thanks for the roll!', translation: 'Obrigado pelo treino!' }],
      dialogue: [{ speaker: 'Student', textEn: 'Hi, I\'m Carlos. Nice to meet you.', textPt: 'Oi, sou o Carlos. Prazer.' }] },
    { id: 'lsn-03', courseId: 'crs-white-belt', order: 3, title: 'Gi Parts', summaryPt: 'Partes do kimono em inglês.',
      phrases: [{ phrase: 'Gi Jacket', translation: 'Jaqueta do kimono' }, { phrase: 'Collar / Lapel', translation: 'Gola / Lapela' }, { phrase: 'Sleeves / Pants / Belt', translation: 'Mangas / Calças / Faixa' }, { phrase: 'Grip the collar and sleeve', translation: 'Segure a gola e a manga' }],
      dialogue: [{ speaker: 'Raphaela', textEn: 'Grip the collar and sleeve. Tie your belt.', textPt: 'Segure a gola e manga. Amarre sua faixa.' }] },
    { id: 'lsn-04', courseId: 'crs-white-belt', order: 4, title: 'Belt Colors & Ranks', summaryPt: 'Cores das faixas e graduações.',
      phrases: [{ phrase: 'White Belt / Blue Belt / Purple Belt / Brown Belt / Black Belt', translation: 'Faixa Branca / Azul / Roxa / Marrom / Preta' }, { phrase: 'Stripes', translation: 'Graus' }, { phrase: 'I am a white belt with two stripes', translation: 'Sou faixa branca com dois graus' }],
      dialogue: [] },
    { id: 'lsn-05', courseId: 'crs-white-belt', order: 5, title: 'Body Parts', summaryPt: 'Partes do corpo essenciais para instrução.',
      phrases: [{ phrase: 'Head / Neck / Shoulder / Arm / Elbow', translation: 'Cabeça / Pescoço / Ombro / Braço / Cotovelo' }, { phrase: 'Wrist / Hand / Hip / Leg / Knee / Ankle / Foot', translation: 'Pulso / Mão / Quadril / Perna / Joelho / Tornozelo / Pé' }, { phrase: 'Control the head and shoulder', translation: 'Controle a cabeça e o ombro' }],
      dialogue: [] },
    { id: 'lsn-06', courseId: 'crs-white-belt', order: 6, title: 'Directions', summaryPt: 'Termos de direção no tatame.',
      phrases: [{ phrase: 'Left / Right / Forward / Backward', translation: 'Esquerda / Direita / Frente / Trás' }, { phrase: 'Up / Down / Inside / Outside', translation: 'Cima / Baixo / Dentro / Fora' }, { phrase: 'Step forward with your left leg', translation: 'Dê um passo à frente com a perna esquerda' }],
      dialogue: [] },
    { id: 'lsn-07', courseId: 'crs-white-belt', order: 7, title: 'Basic Positions', summaryPt: 'Posições fundamentais do Jiu-Jitsu.',
      phrases: [{ phrase: 'Guard / Mount / Side Control', translation: 'Guarda / Montada / Controle Lateral' }, { phrase: 'Back Control / Turtle', translation: 'Pegada de Costas / Tartaruga' }, { phrase: 'I am in guard position', translation: 'Estou na posição de guarda' }, { phrase: 'He passed to side control', translation: 'Ele passou para o controle lateral' }],
      dialogue: [] },
    { id: 'lsn-08', courseId: 'crs-white-belt', order: 8, title: 'Warm-up Vocabulary', summaryPt: 'Vocabulário de aquecimento.',
      phrases: [{ phrase: 'Jogging / Jumping jacks', translation: 'Corrida leve / Polichinelos' }, { phrase: 'Forward roll / Backward roll', translation: 'Rolamento frente / Rolamento trás' }, { phrase: 'Hip escape / Breakfall', translation: 'Fuga de quadril / Queda' }],
      dialogue: [] },
    { id: 'lsn-09', courseId: 'crs-white-belt', order: 9, title: 'Common Verbs', summaryPt: 'Verbos de ação essenciais.',
      phrases: [{ phrase: 'Push / Pull / Hold / Release', translation: 'Empurrar / Puxar / Segurar / Soltar' }, { phrase: 'Turn / Step / Bridge / Tap', translation: 'Virar / Dar passo / Ponte / Bater' }, { phrase: 'When you feel pain, tap out', translation: 'Quando sentir dor, bata' }],
      dialogue: [] },
    { id: 'lsn-10', courseId: 'crs-white-belt', order: 10, title: 'Instructor Commands', summaryPt: 'Comandos do professor durante o treino.',
      phrases: [{ phrase: 'Stop! / Time! / Switch!', translation: 'Pare! / Tempo! / Troca!' }, { phrase: 'Line up! / Listen! / Pay attention!', translation: 'Enfileirem-se! / Escutem! / Prestem atenção!' }, { phrase: 'Line up by belt rank!', translation: 'Enfileirem-se por graduação!' }],
      dialogue: [] },
    { id: 'lsn-11', courseId: 'crs-white-belt', order: 11, title: 'Partner Commands', summaryPt: 'Frases para usar com o parceiro.',
      phrases: [{ phrase: 'Ready? / Let\'s roll / Light roll', translation: 'Pronto? / Vamos treinar / Treino leve' }, { phrase: 'Go easy / Reset', translation: 'Vá com calma / Volta posição' }, { phrase: 'Can we do a light roll?', translation: 'Podemos fazer um treino leve?' }],
      dialogue: [] },
    { id: 'lsn-12', courseId: 'crs-white-belt', order: 12, title: 'Counting & Time', summaryPt: 'Contagem e termos de tempo.',
      phrases: [{ phrase: 'One through Ten', translation: 'Um a Dez' }, { phrase: 'Round / Minute / Seconds / Timer', translation: 'Round / Minuto / Segundos / Cronômetro' }, { phrase: 'Five-minute round with one-minute rest', translation: 'Round de 5 min com 1 min de descanso' }],
      dialogue: [] },
    { id: 'lsn-13', courseId: 'crs-white-belt', order: 13, title: 'Training Equipment', summaryPt: 'Equipamentos de treino.',
      phrases: [{ phrase: 'Mouthguard / Rashguard / Ear guard', translation: 'Protetor bucal / Camisa lycra / Protetor orelha' }, { phrase: 'Athletic tape / Water bottle', translation: 'Esparadrapo / Garrafa d\'água' }, { phrase: 'Put on your mouthguard before sparring', translation: 'Coloque o protetor antes do treino' }],
      dialogue: [] },
    { id: 'lsn-14', courseId: 'crs-white-belt', order: 14, title: 'Academy Vocabulary', summaryPt: 'Vocabulário da academia.',
      phrases: [{ phrase: 'Locker room / Mat space / Front desk', translation: 'Vestiário / Área de tatame / Recepção' }, { phrase: 'Schedule / Open mat', translation: 'Grade de horários / Tatame livre' }, { phrase: 'Is there an open mat on Saturday?', translation: 'Tem tatame livre no sábado?' }],
      dialogue: [] },
    { id: 'lsn-15', courseId: 'crs-white-belt', order: 15, title: 'Simple Questions', summaryPt: 'Perguntas simples em inglês.',
      phrases: [{ phrase: 'How do I do this?', translation: 'Como eu faço isso?' }, { phrase: 'Can you repeat?', translation: 'Pode repetir?' }, { phrase: 'Which arm? / Where do I put my hand?', translation: 'Qual braço? / Onde coloco minha mão?' }],
      dialogue: [] },
    { id: 'lsn-16', courseId: 'crs-white-belt', order: 16, title: 'Simple Answers', summaryPt: 'Respostas diretas no tatame.',
      phrases: [{ phrase: 'Got it! / I understand / I don\'t know', translation: 'Entendi! / Eu entendo / Não sei' }, { phrase: 'Like this? / Like that', translation: 'Assim? / Assim mesmo' }],
      dialogue: [] },
    { id: 'lsn-17', courseId: 'crs-white-belt', order: 17, title: 'Talking About Yourself', summaryPt: 'Como falar sobre sua experiência.',
      phrases: [{ phrase: 'I have been training for six months', translation: 'Treino há seis meses' }, { phrase: 'My instructor is Professor Silva', translation: 'Meu professor é o Professor Silva' }, { phrase: 'I train three times a week', translation: 'Treino três vezes por semana' }],
      dialogue: [] },
    { id: 'lsn-18', courseId: 'crs-white-belt', order: 18, title: 'Daily Training Routine', summaryPt: 'Rotina da aula.',
      phrases: [{ phrase: 'First we warm up', translation: 'Primeiro aquecemos' }, { phrase: 'Then we practice techniques', translation: 'Depois praticamos técnicas' }, { phrase: 'Finally we roll', translation: 'Por fim, treino livre' }],
      dialogue: [] },
    { id: 'lsn-19', courseId: 'crs-white-belt', order: 19, title: 'Review & Conversation', summaryPt: 'Diálogo reunindo tudo.',
      phrases: [{ phrase: 'Hello! Ready to roll?', translation: 'Olá! Pronto pra treinar?' }, { phrase: 'Great, grab the sleeves and let\'s start!', translation: 'Ótimo, pegue as mangas e vamos!' }],
      dialogue: [{ speaker: 'Student', textEn: 'Yes, let\'s do a light roll.', textPt: 'Sim, vamos fazer um treino leve.' }] },
    { id: 'lsn-20', courseId: 'crs-white-belt', order: 20, title: 'White Belt Challenge', summaryPt: 'Desafio: apresente-se, explique regras e convide pra treinar — tudo em inglês.',
      phrases: [{ phrase: 'Introduce yourself and explain mat etiquette entirely in English', translation: 'Apresente-se e explique a etiqueta do tatame inteiramente em inglês' }],
      dialogue: [] },

    // ─── MODULE 2: BLUE BELT (Technique English) ───
    { id: 'lsn-21', courseId: 'crs-blue-belt', order: 1, title: 'Closed Guard', summaryPt: 'Guarda Fechada: manter, quebrar postura, controlar.',
      phrases: [{ phrase: 'Cross your feet behind their back', translation: 'Cruze os pés atrás das costas' }, { phrase: 'Break their posture', translation: 'Quebre a postura' }, { phrase: 'Control collar and sleeves', translation: 'Controle gola e mangas' }],
      dialogue: [] },
    { id: 'lsn-22', courseId: 'crs-blue-belt', order: 2, title: 'Open Guard', summaryPt: 'Guarda Aberta: pés no quadril, controle de distância.',
      phrases: [{ phrase: 'Place feet on hips', translation: 'Pés no quadril' }, { phrase: 'Keep distance', translation: 'Mantenha distância' }, { phrase: 'Control wrists', translation: 'Controle os pulsos' }, { phrase: 'Manage distance with frames', translation: 'Gerencie distância com frames' }],
      dialogue: [] },
    { id: 'lsn-23', courseId: 'crs-blue-belt', order: 3, title: 'Half Guard', summaryPt: 'Meia-Guarda: underhook, knee shield.',
      phrases: [{ phrase: 'Underhook / Overhook', translation: 'Esgrima por baixo / por cima' }, { phrase: 'Knee shield', translation: 'Escudo de joelho' }, { phrase: 'Get a deep underhook', translation: 'Pegue uma esgrima profunda' }],
      dialogue: [] },
    { id: 'lsn-24', courseId: 'crs-blue-belt', order: 4, title: 'Spider Guard', summaryPt: 'Guarda Aranha.',
      phrases: [{ phrase: 'Sleeve grips', translation: 'Pegadas de manga' }, { phrase: 'Feet on biceps', translation: 'Pés no bíceps' }, { phrase: 'Extend one leg while retracting the other', translation: 'Estenda uma perna enquanto recolhe a outra' }],
      dialogue: [] },
    { id: 'lsn-25', courseId: 'crs-blue-belt', order: 5, title: 'De La Riva Guard', summaryPt: 'Guarda De La Riva.',
      phrases: [{ phrase: 'Hook the lead leg', translation: 'Gancho na perna da frente' }, { phrase: 'Heel grip', translation: 'Pegada no calcanhar' }, { phrase: 'Control the opposite sleeve', translation: 'Controle a manga oposta' }],
      dialogue: [] },
    { id: 'lsn-26', courseId: 'crs-blue-belt', order: 6, title: 'Mount', summaryPt: 'Montada: high mount, S-mount, heavy hips.',
      phrases: [{ phrase: 'High mount / S-mount', translation: 'Montada alta / Montada em S' }, { phrase: 'Heavy hips', translation: 'Quadril pesado' }, { phrase: 'Maintain balance', translation: 'Manter equilíbrio' }, { phrase: 'Drop your heavy hips onto their pelvis', translation: 'Solte o quadril pesado na bacia' }],
      dialogue: [] },
    { id: 'lsn-27', courseId: 'crs-blue-belt', order: 7, title: 'Side Control', summaryPt: 'Controle Lateral / 100 Kilos.',
      phrases: [{ phrase: 'Crossface', translation: 'Pressão de ombro no rosto' }, { phrase: 'Chest to chest', translation: 'Peito com peito' }, { phrase: 'Block the hip', translation: 'Bloquear o quadril' }],
      dialogue: [] },
    { id: 'lsn-28', courseId: 'crs-blue-belt', order: 8, title: 'North-South', summaryPt: 'Posição Norte-Sul.',
      phrases: [{ phrase: 'Inverse head alignment', translation: 'Alinhamento oposto da cabeça' }, { phrase: 'Over-under arm control', translation: 'Controle por cima e por baixo' }, { phrase: 'Heavy shoulder pressure', translation: 'Pressão pesada do ombro' }],
      dialogue: [] },
    { id: 'lsn-29', courseId: 'crs-blue-belt', order: 9, title: 'Back Control', summaryPt: 'Pegada de Costas.',
      phrases: [{ phrase: 'Seatbelt grip', translation: 'Cinto de segurança' }, { phrase: 'Hooks in', translation: 'Ganchos para dentro' }, { phrase: 'Body triangle', translation: 'Triângulo de corpo' }, { phrase: 'Do not cross your feet', translation: 'Não cruze os pés' }],
      dialogue: [] },
    { id: 'lsn-30', courseId: 'crs-blue-belt', order: 10, title: 'Turtle Position', summaryPt: 'Posição de Tartaruga.',
      phrases: [{ phrase: 'Tuck your head', translation: 'Esconda a cabeça' }, { phrase: 'Protect the neck', translation: 'Proteja o pescoço' }, { phrase: 'Clock choke entry', translation: 'Entrada para estrangulamento relógio' }],
      dialogue: [] },
    { id: 'lsn-31', courseId: 'crs-blue-belt', order: 11, title: 'Guard Passing', summaryPt: 'Passagens de Guarda.',
      phrases: [{ phrase: 'Toreando pass', translation: 'Passagem toreando' }, { phrase: 'Knee slice pass', translation: 'Passagem cortando joelho' }, { phrase: 'Pressure pass / Stack pass', translation: 'Passagem de pressão / Emborcando' }],
      dialogue: [] },
    { id: 'lsn-32', courseId: 'crs-blue-belt', order: 12, title: 'Sweeps', summaryPt: 'Raspagens.',
      phrases: [{ phrase: 'Scissor sweep / Pendulum sweep', translation: 'Tesoura / Pêndulo' }, { phrase: 'Flower sweep', translation: 'Flor' }, { phrase: 'Off-balancing', translation: 'Desequilíbrio' }],
      dialogue: [] },
    { id: 'lsn-33', courseId: 'crs-blue-belt', order: 13, title: 'Escapes', summaryPt: 'Saídas e Defesas.',
      phrases: [{ phrase: 'Bridge and roll', translation: 'Ponte e rolar (Upa)' }, { phrase: 'Hip escape to guard', translation: 'Fuga de quadril pra repor guarda' }, { phrase: 'Frame and create space', translation: 'Fazer frame e criar espaço' }],
      dialogue: [] },
    { id: 'lsn-34', courseId: 'crs-blue-belt', order: 14, title: 'Takedowns', summaryPt: 'Quedas.',
      phrases: [{ phrase: 'Single leg / Double leg', translation: 'Catada de uma perna / Baiana' }, { phrase: 'Hip toss / Sprawl', translation: 'Projeção de quadril / Defesa de queda' }],
      dialogue: [] },
    { id: 'lsn-35', courseId: 'crs-blue-belt', order: 15, title: 'Grip Fighting', summaryPt: 'Luta de Pegadas.',
      phrases: [{ phrase: 'Break the grip', translation: 'Estourar a pegada' }, { phrase: 'Dominant grip', translation: 'Pegada dominante' }, { phrase: 'Sleeve and lapel control', translation: 'Controle de manga e lapela' }],
      dialogue: [] },
    { id: 'lsn-36', courseId: 'crs-blue-belt', order: 16, title: 'Transitions', summaryPt: 'Transições entre posições.',
      phrases: [{ phrase: 'Flow between positions', translation: 'Fluir entre posições' }, { phrase: 'Side control to mount', translation: 'Do 100 kilos pra montada' }, { phrase: 'Guard to back', translation: 'Da guarda pras costas' }],
      dialogue: [] },
    { id: 'lsn-37', courseId: 'crs-blue-belt', order: 17, title: 'Drills', summaryPt: 'Drills de repetição.',
      phrases: [{ phrase: 'Repetition builds muscle memory', translation: 'Repetição constrói memória muscular' }, { phrase: 'Ten reps each side', translation: 'Dez repetições cada lado' }, { phrase: 'Speed drill', translation: 'Drill de velocidade' }],
      dialogue: [] },
    { id: 'lsn-38', courseId: 'crs-blue-belt', order: 18, title: 'Rolling Vocabulary', summaryPt: 'Vocabulário de treino livre.',
      phrases: [{ phrase: 'Pace / Stamina / Pressure', translation: 'Ritmo / Resistência / Pressão' }, { phrase: 'Submission attempt', translation: 'Tentativa de finalização' }],
      dialogue: [] },
    { id: 'lsn-39', courseId: 'crs-blue-belt', order: 19, title: 'Technique Conversation', summaryPt: 'Diálogo técnico.',
      phrases: [{ phrase: 'How did you pass my guard?', translation: 'Como você passou minha guarda?' }, { phrase: 'I established a deep underhook and used a knee slice', translation: 'Eu fiz uma esgrima profunda e usei corte de joelho' }],
      dialogue: [{ speaker: 'Student', textEn: 'How did you pass my guard?', textPt: 'Como passou minha guarda?' }, { speaker: 'Professor', textEn: 'I established a deep underhook and used a knee slice!', textPt: 'Fiz esgrima profunda e usei corte de joelho!' }] },
    { id: 'lsn-40', courseId: 'crs-blue-belt', order: 20, title: 'Blue Belt Challenge', summaryPt: 'Desafio: explique um passo a passo de passagem de guarda em inglês.',
      phrases: [{ phrase: 'Explain a step-by-step guard pass technique entirely in English', translation: 'Explique uma passagem de guarda passo a passo em inglês' }],
      dialogue: [] },

    // ─── MODULE 3: PURPLE BELT (Submission English) ───
    { id: 'lsn-41', courseId: 'crs-purple-belt', order: 1, title: 'Armbar', summaryPt: 'Chave de Braço.',
      phrases: [{ phrase: 'Pinch your knees together', translation: 'Aperte os joelhos' }, { phrase: 'Thumb pointing up', translation: 'Polegar pra cima' }, { phrase: 'Elevate your hips to force the tap', translation: 'Levante o quadril pra forçar a desistência' }],
      dialogue: [] },
    { id: 'lsn-42', courseId: 'crs-purple-belt', order: 2, title: 'Triangle Choke', summaryPt: 'Triângulo.',
      phrases: [{ phrase: 'One arm in, one arm out', translation: 'Um braço dentro, um braço fora' }, { phrase: 'Lock over the shin', translation: 'Trave sobre a canela' }, { phrase: 'Pull the head down', translation: 'Puxe a cabeça' }],
      dialogue: [] },
    { id: 'lsn-43', courseId: 'crs-purple-belt', order: 3, title: 'Kimura', summaryPt: 'Chave Kimura.',
      phrases: [{ phrase: 'Figure-four grip', translation: 'Pegada quatro' }, { phrase: 'Isolate the shoulder joint', translation: 'Isolar a articulação do ombro' }, { phrase: 'Rotate behind the back', translation: 'Rotacionar atrás das costas' }],
      dialogue: [] },
    { id: 'lsn-44', courseId: 'crs-purple-belt', order: 4, title: 'Americana', summaryPt: 'Chave Americana.',
      phrases: [{ phrase: 'Pin the wrist to the mat', translation: 'Pregue o pulso no tatame' }, { phrase: 'Slide elbow down', translation: 'Deslize o cotovelo pra baixo' }, { phrase: 'Paintbrush movement', translation: 'Movimento de pincel' }],
      dialogue: [] },
    { id: 'lsn-45', courseId: 'crs-purple-belt', order: 5, title: 'Rear Naked Choke', summaryPt: 'Mata-Leão.',
      phrases: [{ phrase: 'Wrap the neck deep', translation: 'Envolva o pescoço' }, { phrase: 'Hand on bicep', translation: 'Mão no bíceps' }, { phrase: 'Hide hand behind head', translation: 'Esconda a mão atrás da cabeça' }, { phrase: 'Expand chest', translation: 'Expanda o peito' }],
      dialogue: [] },
    { id: 'lsn-46', courseId: 'crs-purple-belt', order: 6, title: 'Guillotine', summaryPt: 'Guilhotina.',
      phrases: [{ phrase: 'Wrap the chin', translation: 'Envolver o queixo' }, { phrase: 'High-elbow guillotine', translation: 'Guilhotina de cotovelo alto' }, { phrase: 'Crunch abdominal muscles', translation: 'Flexionar abdômen' }],
      dialogue: [] },
    { id: 'lsn-47', courseId: 'crs-purple-belt', order: 7, title: 'Cross Collar Choke', summaryPt: 'Estrangulamento Cruzado.',
      phrases: [{ phrase: 'Deep grips in collar', translation: 'Pegadas profundas na gola' }, { phrase: 'Palms up', translation: 'Palmas pra cima' }, { phrase: 'Pull elbows to body', translation: 'Cotovelos no corpo' }],
      dialogue: [] },
    { id: 'lsn-48', courseId: 'crs-purple-belt', order: 8, title: 'Bow and Arrow Choke', summaryPt: 'Arco e Flecha.',
      phrases: [{ phrase: 'Collar grip and pant grip', translation: 'Pegada na gola e calça' }, { phrase: 'Leg over shoulder', translation: 'Perna no ombro' }, { phrase: 'Pull like a bow', translation: 'Puxar como um arco' }],
      dialogue: [] },
    { id: 'lsn-49', courseId: 'crs-purple-belt', order: 9, title: 'Ezekiel Choke', summaryPt: 'Ezequiel.',
      phrases: [{ phrase: 'Slide hand inside your sleeve', translation: 'Deslize a mão por dentro da manga' }, { phrase: 'Press forearm across the throat', translation: 'Pressione antebraço no pescoço' }],
      dialogue: [] },
    { id: 'lsn-50', courseId: 'crs-purple-belt', order: 10, title: 'Omoplata', summaryPt: 'Omoplata.',
      phrases: [{ phrase: 'Trap the arm with legs', translation: 'Prender braço com as pernas' }, { phrase: 'Sit up and break base', translation: 'Sentar e quebrar base' }, { phrase: 'Drive hips forward', translation: 'Projetar quadril' }],
      dialogue: [] },
    { id: 'lsn-51', courseId: 'crs-purple-belt', order: 11, title: 'Straight Ankle Lock', summaryPt: 'Chave de Pé Reta.',
      phrases: [{ phrase: 'Wrap Achilles tendon', translation: 'Envolver tendão de Aquiles' }, { phrase: 'Arch your back', translation: 'Arquear as costas' }],
      dialogue: [] },
    { id: 'lsn-52', courseId: 'crs-purple-belt', order: 12, title: 'Kneebar', summaryPt: 'Chave de Joelho.',
      phrases: [{ phrase: 'Isolate leg between thighs', translation: 'Isolar perna nas coxas' }, { phrase: 'Hug the leg', translation: 'Abraçar a perna' }, { phrase: 'Extend hips back', translation: 'Estender quadril' }],
      dialogue: [] },
    { id: 'lsn-53', courseId: 'crs-purple-belt', order: 13, title: 'Heel Hook Vocabulary', summaryPt: 'Vocabulário de Chave de Calcanhar.',
      phrases: [{ phrase: 'Inside heel hook / Outside heel hook', translation: 'Chave interna / externa' }, { phrase: 'Heel exposure / Leg entanglement', translation: 'Exposição do calcanhar / Emaranhado' }],
      dialogue: [] },
    { id: 'lsn-54', courseId: 'crs-purple-belt', order: 14, title: 'Submission Chains', summaryPt: 'Sequências de finalizações.',
      phrases: [{ phrase: 'Armbar to triangle transition', translation: 'Transição armbar pra triângulo' }, { phrase: 'Triangle to omoplata', translation: 'Triângulo pra omoplata' }],
      dialogue: [] },
    { id: 'lsn-55', courseId: 'crs-purple-belt', order: 15, title: 'Attacking Strategy', summaryPt: 'Estratégia de ataque.',
      phrases: [{ phrase: 'Set up traps', translation: 'Criar armadilhas' }, { phrase: 'Force mistakes', translation: 'Forçar erros' }, { phrase: 'Threaten multiple angles', translation: 'Ameaçar múltiplos ângulos' }],
      dialogue: [] },
    { id: 'lsn-56', courseId: 'crs-purple-belt', order: 16, title: 'Defending Submissions', summaryPt: 'Defesa de finalizações.',
      phrases: [{ phrase: 'Early defense / Late defense', translation: 'Defesa precoce / tardia' }, { phrase: 'Clear grips before it locks', translation: 'Desfazer pegadas antes de travar' }],
      dialogue: [] },
    { id: 'lsn-57', courseId: 'crs-purple-belt', order: 17, title: 'Explaining Techniques', summaryPt: 'Como ensinar técnicas.',
      phrases: [{ phrase: 'First step is...', translation: 'O primeiro passo é...' }, { phrase: 'Next, you want to...', translation: 'Em seguida...' }, { phrase: 'Make sure you don\'t...', translation: 'Garanta que não...' }],
      dialogue: [] },
    { id: 'lsn-58', courseId: 'crs-purple-belt', order: 18, title: 'Correcting Mistakes', summaryPt: 'Corrigindo erros.',
      phrases: [{ phrase: 'Your elbow is too far out', translation: 'Seu cotovelo está muito aberto' }, { phrase: 'Tighten your knees', translation: 'Aperte seus joelhos' }],
      dialogue: [] },
    { id: 'lsn-59', courseId: 'crs-purple-belt', order: 19, title: 'Technique Discussion', summaryPt: 'Discussão técnica.',
      phrases: [{ phrase: 'Why is this triangle not working?', translation: 'Por que esse triângulo não funciona?' }, { phrase: 'Adjust your body angle to 90 degrees', translation: 'Ajuste o ângulo do corpo pra 90 graus' }],
      dialogue: [] },
    { id: 'lsn-60', courseId: 'crs-purple-belt', order: 20, title: 'Purple Belt Challenge', summaryPt: 'Desafio: ensine duas finalizações encadeadas em inglês.',
      phrases: [{ phrase: 'Teach a two-submission combination fluidly in English', translation: 'Ensine uma combinação de duas finalizações em inglês' }],
      dialogue: [] },

    // ─── MODULE 4: BROWN BELT (Competition English) ───
    { id: 'lsn-61', courseId: 'crs-brown-belt', order: 1, title: 'Competition Registration', summaryPt: 'Inscrição em torneios.',
      phrases: [{ phrase: 'Weight class / Age division', translation: 'Categoria de peso / Divisão de idade' }, { phrase: 'Open class / Absolute', translation: 'Categoria Absoluto' }],
      dialogue: [] },
    { id: 'lsn-62', courseId: 'crs-brown-belt', order: 2, title: 'Weigh-in', summaryPt: 'Pesagem.',
      phrases: [{ phrase: 'Weigh-in with Gi on', translation: 'Pesagem com kimono' }, { phrase: 'Make weight on first attempt', translation: 'Bater o peso na primeira' }],
      dialogue: [] },
    { id: 'lsn-63', courseId: 'crs-brown-belt', order: 3, title: 'IBJJF Vocabulary', summaryPt: 'Regras IBJJF.',
      phrases: [{ phrase: 'Rulebook / Disqualification (DQ)', translation: 'Livreto de regras / Desclassificação' }, { phrase: 'Illegal move / Uniform check', translation: 'Movimento ilegal / Checagem de kimono' }],
      dialogue: [] },
    { id: 'lsn-64', courseId: 'crs-brown-belt', order: 4, title: 'Scoring System', summaryPt: 'Sistema de pontuação.',
      phrases: [{ phrase: 'Takedown 2pts / Sweep 2pts / Guard Pass 3pts', translation: 'Queda 2pts / Raspagem 2pts / Passagem 3pts' }, { phrase: 'Mount 4pts / Back Control 4pts / Knee on belly 2pts', translation: 'Montada 4pts / Costas 4pts / Joelho na barriga 2pts' }],
      dialogue: [] },
    { id: 'lsn-65', courseId: 'crs-brown-belt', order: 5, title: 'Advantages', summaryPt: 'Vantagens.',
      phrases: [{ phrase: 'Near submission / Near sweep', translation: 'Quase finalização / Quase raspagem' }, { phrase: 'Advantage awarded', translation: 'Vantagem concedida' }],
      dialogue: [] },
    { id: 'lsn-66', courseId: 'crs-brown-belt', order: 6, title: 'Penalties', summaryPt: 'Punições.',
      phrases: [{ phrase: 'Stalling', translation: 'Amarrar a luta' }, { phrase: 'Out of bounds / Fleeing the mat', translation: 'Sair do tatame / Fugir do tatame' }],
      dialogue: [] },
    { id: 'lsn-67', courseId: 'crs-brown-belt', order: 7, title: 'Referee Commands', summaryPt: 'Comandos de arbitragem.',
      phrases: [{ phrase: 'Combate! / Parou! / Lute! / Tempo!', translation: 'Combate! / Parou! / Lute! / Tempo!' }],
      dialogue: [] },
    { id: 'lsn-68', courseId: 'crs-brown-belt', order: 8, title: 'Coach Instructions', summaryPt: 'Gritos do corner.',
      phrases: [{ phrase: 'Breathe! / Heavy base!', translation: 'Respire! / Base pesada!' }, { phrase: 'Score now! / Hold the position!', translation: 'Pontue! / Segure a posição!' }],
      dialogue: [] },
    { id: 'lsn-69', courseId: 'crs-brown-belt', order: 9, title: 'Match Strategy', summaryPt: 'Estratégia de luta.',
      phrases: [{ phrase: 'Pull guard or takedown?', translation: 'Puxar guarda ou dar queda?' }, { phrase: 'Impose your game plan', translation: 'Impor seu plano de jogo' }],
      dialogue: [] },
    { id: 'lsn-70', courseId: 'crs-brown-belt', order: 10, title: 'Game Plan', summaryPt: 'Plano de jogo.',
      phrases: [{ phrase: 'Prepare a Plan A and Plan B', translation: 'Prepare um Plano A e B' }, { phrase: 'Play to your strengths', translation: 'Jogue nos seus pontos fortes' }],
      dialogue: [] },
    { id: 'lsn-71', courseId: 'crs-brown-belt', order: 11, title: 'Managing the Clock', summaryPt: 'Gerenciando o tempo.',
      phrases: [{ phrase: 'Two minutes left', translation: 'Faltam dois minutos' }, { phrase: 'Protect your score lead', translation: 'Proteja sua liderança no placar' }],
      dialogue: [] },
    { id: 'lsn-72', courseId: 'crs-brown-belt', order: 12, title: 'Winning by Submission', summaryPt: 'Vitória por finalização.',
      phrases: [{ phrase: 'Clean finish / Tap out victory', translation: 'Finalização limpa / Vitória por desistência' }],
      dialogue: [] },
    { id: 'lsn-73', courseId: 'crs-brown-belt', order: 13, title: 'Winning by Points', summaryPt: 'Vitória por pontos.',
      phrases: [{ phrase: 'Win by decision / Scoreboard lead', translation: 'Vitória por decisão / Liderança no placar' }],
      dialogue: [] },
    { id: 'lsn-74', courseId: 'crs-brown-belt', order: 14, title: 'Interviews', summaryPt: 'Entrevista pós-luta.',
      phrases: [{ phrase: 'I feel amazing', translation: 'Me sinto incrível' }, { phrase: 'Thanks to my professor, team, and sponsors', translation: 'Agradeço ao meu professor, equipe e patrocinadores' }],
      dialogue: [] },
    { id: 'lsn-75', courseId: 'crs-brown-belt', order: 15, title: 'Seminars', summaryPt: 'Promovendo seminários.',
      phrases: [{ phrase: 'Hosting a seminar / Registration fee', translation: 'Sediar um seminário / Taxa de inscrição' }],
      dialogue: [] },
    { id: 'lsn-76', courseId: 'crs-brown-belt', order: 16, title: 'Travel Vocabulary', summaryPt: 'Vocabulário de viagem.',
      phrases: [{ phrase: 'Passport / Visa / Flight connection', translation: 'Passaporte / Visto / Conexão de voo' }, { phrase: 'Hotel check-in', translation: 'Check-in no hotel' }],
      dialogue: [] },
    { id: 'lsn-77', courseId: 'crs-brown-belt', order: 17, title: 'Training Camp', summaryPt: 'Camp de treino.',
      phrases: [{ phrase: 'High-intensity sparring / Conditioning', translation: 'Treino de alta intensidade / Preparação física' }],
      dialogue: [] },
    { id: 'lsn-78', courseId: 'crs-brown-belt', order: 18, title: 'Competition Conversation', summaryPt: 'Diálogo de torneio.',
      phrases: [{ phrase: 'How did your matches go?', translation: 'Como foram suas lutas?' }, { phrase: 'I won three fights, two by submission, and took gold!', translation: 'Ganhei três lutas, duas por finalização, e levei o ouro!' }],
      dialogue: [] },
    { id: 'lsn-79', courseId: 'crs-brown-belt', order: 19, title: 'International Academy', summaryPt: 'Visitando academias no exterior.',
      phrases: [{ phrase: 'Drop-in fee / Visitor etiquette', translation: 'Taxa de aula avulsa / Etiqueta de visitante' }],
      dialogue: [] },
    { id: 'lsn-80', courseId: 'crs-brown-belt', order: 20, title: 'Brown Belt Challenge', summaryPt: 'Desafio: simule uma entrevista de campeão mundial em inglês.',
      phrases: [{ phrase: 'Simulate a full post-fight world champion interview in English', translation: 'Simule uma entrevista completa de campeão em inglês' }],
      dialogue: [] },

    // ─── MODULE 5: BLACK BELT (Instructor English) ───
    { id: 'lsn-81', courseId: 'crs-black-belt', order: 1, title: 'Teaching Basics', summaryPt: 'Liderando a turma.',
      phrases: [{ phrase: 'Gather around, everyone!', translation: 'Aproximem-se, todos!' }, { phrase: 'Eyes on me', translation: 'Atenção em mim' }, { phrase: 'Today we are covering...', translation: 'Hoje vamos trabalhar...' }],
      dialogue: [] },
    { id: 'lsn-82', courseId: 'crs-black-belt', order: 2, title: 'Explaining Techniques Clearly', summaryPt: 'Explicação clara em 3 passos.',
      phrases: [{ phrase: 'Break down into three main steps', translation: 'Dividir em três passos' }, { phrase: 'Grip placement, hip movement, finishing pressure', translation: 'Posição da pegada, movimento de quadril, pressão final' }],
      dialogue: [] },
    { id: 'lsn-83', courseId: 'crs-black-belt', order: 3, title: 'Giving Instructions', summaryPt: 'Comando de prática.',
      phrases: [{ phrase: 'Do five reps each, then switch roles', translation: 'Façam 5 cada um, depois troquem' }, { phrase: 'Increase resistance gradually', translation: 'Aumentem a resistência aos poucos' }],
      dialogue: [] },
    { id: 'lsn-84', courseId: 'crs-black-belt', order: 4, title: 'Correcting Students', summaryPt: 'Correção técnica construtiva.',
      phrases: [{ phrase: 'Great attempt, but adjust your hip position slightly', translation: 'Boa tentativa, mas ajuste o quadril' }, { phrase: 'Try it like this', translation: 'Tente assim' }],
      dialogue: [] },
    { id: 'lsn-85', courseId: 'crs-black-belt', order: 5, title: 'Motivating Students', summaryPt: 'Motivação.',
      phrases: [{ phrase: 'Keep pushing! / Great job!', translation: 'Continue firme! / Ótimo trabalho!' }, { phrase: 'Don\'t give up now, you have one minute left!', translation: 'Não desista, falta um minuto!' }],
      dialogue: [] },
    { id: 'lsn-86', courseId: 'crs-black-belt', order: 6, title: 'Managing a Class', summaryPt: 'Gestão de tatame.',
      phrases: [{ phrase: 'Spread out across the mat space', translation: 'Espalhem-se pelo tatame' }, { phrase: 'Watch your surroundings to keep everyone safe', translation: 'Cuidado com o espaço' }],
      dialogue: [] },
    { id: 'lsn-87', courseId: 'crs-black-belt', order: 7, title: 'Kids Class', summaryPt: 'Aulas infantis.',
      phrases: [{ phrase: 'Listen up, superheroes!', translation: 'Atenção, super-heróis!' }, { phrase: 'Sit criss-cross applesauce', translation: 'Sentar de pernas cruzadas' }],
      dialogue: [] },
    { id: 'lsn-88', courseId: 'crs-black-belt', order: 8, title: 'Adult Class', summaryPt: 'Aulas para adultos.',
      phrases: [{ phrase: 'Fundamentals curriculum / Advanced concepts', translation: 'Currículo de fundamentos / Conceitos avançados' }],
      dialogue: [] },
    { id: 'lsn-89', courseId: 'crs-black-belt', order: 9, title: 'Private Lessons', summaryPt: 'Aulas particulares.',
      phrases: [{ phrase: 'Tailored instruction', translation: 'Instrução personalizada' }, { phrase: 'Identify and fix weaknesses', translation: 'Identificar e corrigir pontos fracos' }],
      dialogue: [] },
    { id: 'lsn-90', courseId: 'crs-black-belt', order: 10, title: 'Advanced Concepts', summaryPt: 'Conceitos avançados.',
      phrases: [{ phrase: 'Mechanical leverage and fulcrum', translation: 'Alavanca mecânica e ponto de apoio' }, { phrase: 'Weight distribution', translation: 'Distribuição de peso' }],
      dialogue: [] },
    { id: 'lsn-91', courseId: 'crs-black-belt', order: 11, title: 'Answering Questions', summaryPt: 'Respondendo dúvidas.',
      phrases: [{ phrase: 'That\'s a great question!', translation: 'Ótima pergunta!' }, { phrase: 'If your opponent counters, here is your solution', translation: 'Se o oponente defender, aqui está a solução' }],
      dialogue: [] },
    { id: 'lsn-92', courseId: 'crs-black-belt', order: 12, title: 'Running Drills', summaryPt: 'Treinos situacionais.',
      phrases: [{ phrase: 'Specific sparring / King of the mat', translation: 'Treino específico / Rei do tatame' }, { phrase: 'Start from closed guard', translation: 'Começar da guarda fechada' }],
      dialogue: [] },
    { id: 'lsn-93', courseId: 'crs-black-belt', order: 13, title: 'Seminars', summaryPt: 'Ministrando seminários.',
      phrases: [{ phrase: 'Welcome to today\'s masterclass!', translation: 'Bem-vindos à masterclass de hoje!' }, { phrase: 'Today I will share my complete lapel guard system', translation: 'Hoje vou compartilhar meu sistema completo de guarda de lapela' }],
      dialogue: [] },
    { id: 'lsn-94', courseId: 'crs-black-belt', order: 14, title: 'Receiving Foreign Students', summaryPt: 'Acolhendo estrangeiros.',
      phrases: [{ phrase: 'Welcome to our academy!', translation: 'Bem-vindo à nossa academia!' }, { phrase: 'Feel at home', translation: 'Sinta-se em casa' }],
      dialogue: [] },
    { id: 'lsn-95', courseId: 'crs-black-belt', order: 15, title: 'Opening Your Academy', summaryPt: 'Gestão de academia.',
      phrases: [{ phrase: 'Membership plans / Digital waiver form', translation: 'Planos de matrícula / Termo digital' }, { phrase: 'Class schedule', translation: 'Grade de horários' }],
      dialogue: [] },
    { id: 'lsn-96', courseId: 'crs-black-belt', order: 16, title: 'Teaching Online', summaryPt: 'Cursos online.',
      phrases: [{ phrase: 'Welcome back to my online instructional series!', translation: 'Bem-vindos de volta à minha série de aulas online!' }, { phrase: 'Today we break down the leg drag pass', translation: 'Hoje vamos detalhar a passagem leg drag' }],
      dialogue: [] },
    { id: 'lsn-97', courseId: 'crs-black-belt', order: 17, title: 'Professional Vocabulary', summaryPt: 'Vocabulário profissional do head coach.',
      phrases: [{ phrase: 'Mat culture / Student retention', translation: 'Cultura do tatame / Retenção de alunos' }, { phrase: 'Clear pedagogy / Leadership', translation: 'Pedagogia clara / Liderança' }],
      dialogue: [] },
    { id: 'lsn-98', courseId: 'crs-black-belt', order: 18, title: 'Complete Class Simulation', summaryPt: 'Simulação de aula completa.',
      phrases: [{ phrase: 'Line up! Warm-up complete.', translation: 'Enfileirem-se! Aquecimento completo.' }, { phrase: 'Technique practice 30min. Sparring 20min. Bow out!', translation: 'Técnica 30min. Treino livre 20min. Saudação!' }],
      dialogue: [] },
    { id: 'lsn-99', courseId: 'crs-black-belt', order: 19, title: 'Final Review', summaryPt: 'Revisão geral do módulo instrutor.',
      phrases: [{ phrase: 'Clear explanations / Positive leadership', translation: 'Explicações claras / Liderança positiva' }, { phrase: 'Mat safety / Teaching adaptability', translation: 'Segurança no tatame / Adaptabilidade' }],
      dialogue: [] },
    { id: 'lsn-100', courseId: 'crs-black-belt', order: 20, title: 'Black Belt Graduation', summaryPt: 'Formatura: discurso final do curso.',
      phrases: [{ phrase: 'Congratulations on completing all 100 lessons of English for Jiu-Jitsu!', translation: 'Parabéns por completar todas as 100 aulas!' }, { phrase: 'You are fully prepared to teach, compete, and share Jiu-Jitsu anywhere in the world in English. Oss!', translation: 'Você está totalmente preparado para ensinar, competir e compartilhar Jiu-Jitsu em qualquer lugar do mundo em inglês. Oss!' }],
      dialogue: [] },
  ];

  for (const l of lessons) {
    db.run(
      `INSERT OR IGNORE INTO lessons (id, courseId, moduleOrder, title, summaryPt, keyPhrasesJson, dialogueExamplesJson, createdAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [l.id, l.courseId, l.order, l.title, l.summaryPt, JSON.stringify(l.phrases), JSON.stringify(l.dialogue), now]
    );
  }

  console.log('🥋 Currículo "English for Jiu-Jitsu" seedado: 5 cursos, 100 aulas');
}
